#+TITLE: Finite Resources

Using nearly infinite resources are not consuming a finite resource. Therefore, using energy supplied by solar energy do not require using finite resources. Furthermore, if these solar panels have been constructed with solar-energy and peroviskita. The quantity needed of solar-panels wouldn't consume 0.1% of the titanium of the Earth. The other resource is calcium, which is abundant.

So, a trivial one, solar energy business.

Other: knowledge-related workers. Even though they need to eat to live, they don't use any other finite-resource. Trees can be planted sufficiently to print their books, in a rate that you have more trees being planted than used as paper. Etc.

So, another trivial one.

IF you have clean-energy and clean-food, then any electronic-related worker would also be using only infinite resources to live and work.

Actually, the non-trivial examples begin once you state that the energy-matrices and food-matrices are clean as an hypothesis.

The only finite enterprises are those of fossil-fuel related use (mainly american and chinese income-matrices). It makes all following enterprises "dirty" - as opposed to clean.
