* 16 Setembro 2021
O governo dos EUA injeta bilhões de dólares em áreas relacionadas a Ciência, Tecnologia, Engenheria e Matemática (CTEM/STEM)[1].

Se pequisarem, essa é um número normal, para países desenvolvidos (como visto nas fotos). 

A UNESCO diz que um dos grandes desafios que o Brasil enfrenta para melhorar a qualidade de vida da população é o fomento da área de CTEM/STEM [2]. O maior problema sendo a ineficácia de agências brasileiras estruturarem programas incentivando exatas relevantes às necessidade brasileiras[2].

"When it comes to Science, Technology & Innovation management, Brazil relies on a structured system composed of a central coordinating body and development agencies in charge of defining and implementing development policies on science, technology, and innovation. The State and local level Science, Technology & Innovation management systems follow the same model for development policies attuned to regional and local vocations.

(..) above all, [the difficulties are] (...) the scientific and technological knowledge produced is still slow to produce significant changes in the social inequities found in some regions. Therefore, the problems faced by Brazil in the fields of Science, Technology & Innovation are complex and can hardly be solved in the short term."

Esse problema deve ser enfrentado. Um governo e povo sentatos apenas existem em países onde a educação e tecnologias científicas (métodos exatos) são aplicados e incentivados.

As maiores e mais poderosas economias do mundo investem absurdamente nessa área. É assim que países deixam de ser colônia: produzindo sua própria tecnologia.

[1]: https://www.ed.gov/stem
[2]: https://en.unesco.org/fieldoffice/brasilia/expertise/science-technology-innovation

Imagens: https://www.nsf.gov/statistics/2018/nsb20181/report/sections/higher-education-in-science-and-engineering/international-s-e-higher-education
