#+TITLE: Superheros

#+begin_quote
Even God lends a hand to honest boldness.
                -- Menander
#+end_quote

I clearly see people around me haven't aged past kindergarten, they just have
different toys and entertainment.

The fact that documentaries like "Why we fight (7 chapters)" - or movies like
"Society of Spectacle" aren't everyone "bread and butter" - when It comes to
movies; but, as has been pointed out, Super Heroes movies are... Well, It's
sickening (I will link a excerpt on Alan Moore talking about it).

“If you make a movie of the present day culture, in the future it’ll be a horror
film.”, as have said Jacque Fresco. Indeed, he said it decades ago. We haven´t
changed since then.

And, to describe current society is to mock it. That's how bad the state of
affairs are.

"I have a feeling that the current tsunami of American superhero movies is
really not doing our culture any good at all and I would only note that 2016,
the year in which Britain voted for Brexit and in which America elected what
appears to be a gigantic Nazi satsuma, six of the twelve biggest grossing films
were superhero movies. This is bad news for culture.

If we’ve got this infantilization. If we’ve got this refusal to grow up. A
refusal to take responsibility for the adult world in which we all find
ourselves taking part and yes this is a very complex world, and it is scary and
none of us wants to admit that we are now the generation that is in charge of
it.

So we retreat to these fantasies of empowerment, which I previously had a
distaste for after my childhood love. But now I have a kind of toxic aversion to
because I really think that they are damaging culture, I think that they are
damaging the human imagination and I think at the end of the day they could
fairly be described as white supremacist dreams of the master race."

- Alan Moore

https://www.youtube.com/watch?v=YJ3QWnWENNY&t=273s
