#+TITLE: Veblen

Bilingual text.
Texto escrito em inglês e português.

<<Modern Social Structure>>, as view by T. Veblen; a commentary.

I feel a remose, by the modern culture alienation, when I observe classes as: warfare officials, scenic arts, politics, public worship, and public merry-making etc. They are more recognized socio and economically than the working classes which elaborate the material means of life. These are such as, professors, techniques, scientists, public services, agriculture, professionals of the biological, humanities, or exact sciences. It's evident by, for example, a search on youtube most viewed videos.

It simply do not compute that those which mostly produces the goods are less evalued. It, implicitly, says a lot about the culture's model of a desirable life: an state of things such that It's unproductive, exploratory, passive-aggressive, popular, and shallow.

The conspicuous attitudes are behaviors, by excellency, of the members of this culture. That is, there is a inertial movement towards shallow ostentation of all the desirable parameters by society, and individuals - instagram facebook etc prove it. It exposes a false intellectualism, spiritualism , and material goods.

<<Estrutura Social Moderna>>, como observado por T. Veblen; comentário.

Eu sinto remorso, pela alienado da cultura contemporânea, quando observo classes como: oficiais de guerra, encenação, política, veneração de figuras públicas, e programas de encontro de casais etc. São mais reconhecidos socio e monetariamente, do que classes de trabalho as quais possibilitam o manuseamento dos meios materiais da vida, como: professores, ténicos, cientistas, serviços públicos, agricultura, profissionais das áreas biológicas, humanas e exatas. Isto é evidente pelo acesso aos vídeos mais assistidos no youtube, por exemplo.

Simplesmente, não computa que aqueles que mais produzam bens sejam os menos valorizados. Diz muito do que nossa cultura possui como modelo desejável de vida: um estado das coisas que seja improdutivo, exploratório, passivo-agressivo, popular, e raso.

As atitudes conspícuas são os comportamentos, por exelência, de um indivíduo dessa cultura. Isto é, uma moção por ostentação rasa de todos os parametros desejaveis pela sociedade, e indivíduos - instagram, facebook, etc o provam. Exposição de uma falsa intelectualidade e espiritualidade, bem como bens materiais.

https://scontent.faqa2-1.fna.fbcdn.net/v/t1.6435-9/81341075_3279012232173895_7304635989102690304_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=730e14&_nc_eui2=AeH16XowpkhfUBgLdlIzLxn6f-rRn6IeuSp_6tGfoh65Kq9x_RBfcPYVWjHkYXbIlTUwrP94Ug0au-bJTgNkFJJ2&_nc_ohc=QyC0GcRPPKUAX_6O_Ux&_nc_ht=scontent.faqa2-1.fna&oh=00_AT-YZbfXvwYbo7Sc-Ms__zPOSlL5LUNvkc6Y4XloyU8BsQ&oe=61FA228E{:height 152, :width 778}
